[package]
name = "randl-cli"
version = "0.1.0"
authors = ["jam1garner <8260240+jam1garner@users.noreply.github.com>"]
edition = "2018"

[[bin]]
name = "randl"
path = "src/main.rs"

[dependencies]
randl-core = { path = "../randl-core" }
structopt = "0.3"